packages:
  - packages/*

catalog:
  "@elastic/datemath": ^5.0.3
  "@elastic/eui": ^111.0.0
  "@emotion/cache": ^11.14.0
  "@emotion/css": ^11.13.5
  "@emotion/react": ^11.14.0
  "@eslint/compat": ^2.0.0
  "@eslint/eslintrc": ^3.3.3
  "@fluentui/react-icons": ^2.0.316
  "@openapitools/openapi-generator-cli": ^2.26.0
  "@tanstack/react-router": ^1.144.0
  "@tanstack/react-router-devtools": ^1.144.0
  "@tanstack/router-plugin": ^1.145.2
  "@trivago/prettier-plugin-sort-imports": ^6.0.0
  "@types/lodash-es": ^4.17.12
  "@types/node": ^25.0.3
  "@types/nprogress": ^0.2.3
  "@types/qs": ^6.14.0
  "@types/react": ^18.3.27
  "@types/react-dom": ^18.3.7
  "@typescript-eslint/eslint-plugin": ^8.51.0
  "@typescript-eslint/parser": ^8.51.0
  "@typescript/native-preview": 7.0.0-dev.20251212.1
  "@vite-pwa/assets-generator": ^1.0.2
  "@vitejs/plugin-react": ^5.1.2
  ajv: ^8.17.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-config-react-app: ^7.0.1
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-boundaries: ^5.3.1
  eslint-plugin-flowtype: ^8.0.3
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  jsdom: ^27.4.0
  lodash-es: ^4.17.23
  mobx: ^6.15.0
  mobx-react-lite: ^4.1.1
  moment: ^2.30.1
  nprogress: ^0.2.0
  prettier: ^3.7.4
  prop-types: ^15.8.1
  qs: ^6.14.2
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^7.11.0
  react-sortablejs: ^6.1.4
  rimraf: ^6.1.2
  sortablejs: ^1.15.6
  utility-types: ^3.11.0
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-pwa: ^1.2.0
  vitest: ^4.0.16
  workbox-core: ^7.4.0
  workbox-precaching: ^7.4.0
  workbox-routing: ^7.4.0
