/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest
 */
export interface HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest {
    /**
     * 
     * @type {string}
     * @memberof HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest
     */
    name: string;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest(value: object): value is HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestFromJSON(json: any): HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest {
    return HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestToJSON(json: any): HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest {
    return HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestToJSONTyped(value?: HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

