/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto
 */
export interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto {
    /**
     * 
     * @type {string}
     * @memberof HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto
     */
    name: string;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto(value: object): value is HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSONTyped(value?: HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

