/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto } from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto';
import {
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSONTyped,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSONTyped,
} from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto';

/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto
 */
export interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto {
    /**
     * 
     * @type {HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto}
     * @memberof HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto
     */
    playlist: HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto(value: object): value is HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto {
    if (!('playlist' in value) || value['playlist'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoFromJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlist': HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSON(json['playlist']),
    };
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoToJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoToJSONTyped(value?: HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlist': HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSON(value['playlist']),
    };
}

