/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDto } from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDto';
import {
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoFromJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoFromJSONTyped,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoToJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoToJSONTyped,
} from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDto';

/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto
 */
export interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto {
    /**
     * 
     * @type {Array<HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDto>}
     * @memberof HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto
     */
    items: Array<HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDto>;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto(value: object): value is HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoFromJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoFromJSON)),
    };
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoToJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDtoToJSONTyped(value?: HydrangeanDivaMediaPlayerContractsPlaylistsDtosListTracksResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(HydrangeanDivaMediaPlayerContractsPlaylistsDtosTrackDtoToJSON)),
    };
}

