/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest
 */
export interface HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest {
    /**
     * 
     * @type {string}
     * @memberof HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest
     */
    name: string;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest(value: object): value is HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestFromJSON(json: any): HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest {
    return HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestToJSON(json: any): HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest {
    return HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestToJSONTyped(value?: HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

