/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto,
  HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto,
  HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest,
  HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest,
} from '../models/index';
import {
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoFromJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoToJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoFromJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoToJSON,
    HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestFromJSON,
    HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestToJSON,
    HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestFromJSON,
    HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestToJSON,
} from '../models/index';

export interface MediaPlayerPlaylistsIdDeleteRequest {
    id: string;
}

export interface MediaPlayerPlaylistsIdGetRequest {
    id: string;
}

export interface MediaPlayerPlaylistsIdRenamePostRequest {
    id: string;
    hydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest?: HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest;
}

export interface MediaPlayerPlaylistsPostRequest {
    hydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest?: HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest;
}

/**
 * 
 */
export class MediaPlayerPlaylistsApi extends runtime.BaseAPI {

    /**
     */
    async mediaPlayerPlaylistsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/media-player/playlists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async mediaPlayerPlaylistsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto> {
        const response = await this.mediaPlayerPlaylistsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async mediaPlayerPlaylistsIdDeleteRaw(requestParameters: MediaPlayerPlaylistsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaPlayerPlaylistsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/media-player/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async mediaPlayerPlaylistsIdDelete(requestParameters: MediaPlayerPlaylistsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.mediaPlayerPlaylistsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async mediaPlayerPlaylistsIdGetRaw(requestParameters: MediaPlayerPlaylistsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaPlayerPlaylistsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/media-player/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async mediaPlayerPlaylistsIdGet(requestParameters: MediaPlayerPlaylistsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HydrangeanDivaMediaPlayerContractsPlaylistsDtosGetPlaylistResponseDto> {
        const response = await this.mediaPlayerPlaylistsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async mediaPlayerPlaylistsIdRenamePostRaw(requestParameters: MediaPlayerPlaylistsIdRenamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mediaPlayerPlaylistsIdRenamePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/media-player/playlists/{id}:rename`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequestToJSON(requestParameters['hydrangeanDivaMediaPlayerEndpointsPlaylistsRenamePlaylistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async mediaPlayerPlaylistsIdRenamePost(requestParameters: MediaPlayerPlaylistsIdRenamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.mediaPlayerPlaylistsIdRenamePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async mediaPlayerPlaylistsPostRaw(requestParameters: MediaPlayerPlaylistsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/media-player/playlists`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequestToJSON(requestParameters['hydrangeanDivaMediaPlayerEndpointsPlaylistsCreatePlaylistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async mediaPlayerPlaylistsPost(requestParameters: MediaPlayerPlaylistsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.mediaPlayerPlaylistsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
