/* tslint:disable */
/* eslint-disable */
/**
 * HydrangeanDiva
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto } from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto';
import {
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSONTyped,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSON,
    HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSONTyped,
} from './HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto';

/**
 * 
 * @export
 * @interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto
 */
export interface HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto {
    /**
     * 
     * @type {Array<HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto>}
     * @memberof HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto
     */
    items: Array<HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDto>;
}

/**
 * Check if a given object implements the HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto interface.
 */
export function instanceOfHydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto(value: object): value is HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoFromJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoFromJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoFromJSON)),
    };
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoToJSON(json: any): HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto {
    return HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoToJSONTyped(json, false);
}

export function HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDtoToJSONTyped(value?: HydrangeanDivaMediaPlayerContractsPlaylistsDtosListPlaylistsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(HydrangeanDivaMediaPlayerContractsPlaylistsDtosPlaylistDtoToJSON)),
    };
}

